"""Pieces shared by the post-processors."""

import unicodedata
from dataclasses import dataclass

from cnc_warmup import __version__
from cnc_warmup.model import Controller
from cnc_warmup.plan import WarmupPlan, format_duration, format_number


@dataclass(frozen=True)
class Program:
    """A rendered NC program, ready to copy to a control."""

    controller: Controller
    name: str  # as the control knows it, e.g. WARMUP_M1_DAILY or O8001
    filename: str
    text: str  # exact file contents, line endings included

    @property
    def data(self) -> bytes:
        return self.text.encode("ascii")


def ascii_upper(text: str) -> str:
    """Upper-case ASCII: NC controls and file transfer tools reject anything else.

    Accented letters lose their accents. Other non-ASCII characters are dropped.
    """
    decomposed = unicodedata.normalize("NFKD", text)
    return decomposed.encode("ascii", "ignore").decode("ascii").upper()


def describe(plan: WarmupPlan) -> list[str]:
    """Header lines every dialect starts with: what the program does and where it came from."""
    machine, profile, envelope = plan.machine, plan.profile, plan.envelope
    n = format_number
    return [
        f"Warm-up for machine {machine.id}"
        + (f" - {machine.description}" if machine.description else ""),
        f"Profile {profile.name}" + (f" - {profile.description}" if profile.description else ""),
        f"Generated by cnc-warmup {__version__}. Do not edit by hand: regenerate instead.",
        f"Spindle {n(profile.rpm_start)}-{n(profile.rpm_end)} rpm, "
        f"feed {n(profile.feed_start)}-{n(profile.feed_end)} mm/min, "
        f"{profile.stages} stages, {profile.ramp.value} ramp",
        f"Coolant {profile.coolant.value}, edge margin {n(profile.edge_margin_mm)} mm, "
        f"est. run time {format_duration(plan.estimated_seconds)} plus positioning",
        f"Sweep envelope: X {n(envelope.x.min)} to {n(envelope.x.max)}, "
        f"Y {n(envelope.y.min)} to {n(envelope.y.max)}, "
        f"Z {n(envelope.z.min)} to {n(envelope.z.max)}",
    ]


def stage_table(plan: WarmupPlan) -> list[str]:
    """The stage plan as fixed-width text rows."""
    rows = ["Stage     RPM    Feed  Passes  Dwell   Time"]
    for stage in plan.stages:
        dwell = f"{format_number(stage.dwell_seconds)} s"
        rows.append(
            f"{stage.number:>5} {format_number(stage.rpm):>7} {format_number(stage.feed):>7} "
            f"{stage.passes:>7} {dwell:>6} {format_duration(stage.seconds):>6}"
        )
    return rows
